module.exports = {
    PRODUCT_REQUEST_STATE_REQUEST: 'PRODUCT_REQUEST_STATE_REQUEST',
    PRODUCT_REQUEST_STATE_SUCCESS: 'PRODUCT_REQUEST_STATE_SUCCESS',
    PRODUCT_REQUEST_STATE_FAILURE: 'PRODUCT_REQUEST_STATE_FAILURE',
    PRODUCT_FILTER_STATE_REQUEST: 'PRODUCT_FILTER_STATE_REQUEST',
	PRODUCT_FILTER_STATE_SUCCESS: 'PRODUCT_FILTER_STATE_SUCCESS',
	PRODUCT_FILTER_STATE_FAILURE: 'PRODUCT_FILTER_STATE_FAILURE'
};